### PR TITLE
Proposed structure and dynamic sub-page navigation 

### PR DESCRIPTION
**Pull request by lewisnyman**
Implementation of the new IA draft proposed in #16.

I've also reimplemented how subpage navigation is handled, it's not automatic instead of relying on tags.

### CODE REVIEW

**Comment by lewisnyman** [comment]
I've uploaded the site here so it can be tested and reviewed http://wunderway.lewisnyman.co.uk/

**Comment by steveparks** [comment]
This is a great start to making things much clearer.

My thoughts are:

1. Having fewer top level nav items means some things are more clicks away (eg clicking on Working In Projects brings a page with just two items on for now) Maybe we could have a few more things at top level to reduce the journey?
Is there anything you'd promote yet, or maybe that could come later?

2. The front page now seems to have the 'first day' post on it. Is that intentional? I'd prefer it to be used more for signposting and explaining the sections.

3. I'm not sure subpages should be alphabetical - because there is often a logical order. And sometimes maybe we'd want to group items under a heading. But I guess any other way would have to be manual?

**Comment by lewisnyman** [comment]
1. hmm true, how about we move those two up a level, so "Working in projects" becomes "Working in projects" and "Working with clients"

2. This page was originally titled "Reference for Newbies and Wunder Veterans". I think it needs a bit more work so it's not so "first day" centric. 

3. Yeah, we could just make the subpage navigation generation optional, I implemented it mainly to save time while showing off the new IA. Or is there a way we can add to it so it can be customised further? I can't see a way so far.

**Comment by steveparks** [comment]
1. how about:
- Working with Clients
- Delivering Projects

2. could we leave it off the front page then until we have something that's ready?

3. Yeah, I see the sense, and can't see an option other than manual, so let's leave it for now. If it becomes an issue we can always open an issue to review options.

**Comment by WunderLemon** [comment]
1, 2, 3. Yup! Let's split 'Working in Projects' to 'Working with Clients'
and 'Delivery Projects'.
Both of those sections have a lot of content in, and will likely grow.
They're more than strong enough to stand separately.

4. Agreed the front page content is a bit odd at the mo.
I'd like to change it for a couple of short paragraphs explaining what the
WunderWay is (aimed at staff, external users) and how to use it (staff).
I think highlighting why Wunder's transparent about this is important. It's
unusual to have a public intranet, and that in itself is reflective of
Wunder's brand and company style.

5. I agree it'd be better to group headings by logic rather than alphabet,
but I see you mention a snag with this. It's less of an issue since section
menus are shortish for now.
One partial remedy will be for me to rename some pages so their titles are
more explanatory, especially when just viewing in a menu.

6. Can we make the side navigation always visible? Opening it up just means
an extra click to reach any destination.
Also I find as I've moved around (a lot admittedly!) I've lost track of
where I am quite easily – is there a way to highlight location in the nav?

**Comment by lewisnyman** [comment]
Ok I've updated the project IA, both in the sitemap http://bquniy.axshare.com/ and on the demo site wunderway.lewisnyman.co.uk

4. Sounds good, I wouldn't like to focus too much on the WunderWay and save that for the "About the WunderWay" because the primary audience should be internal employees. @WunderLemon would you have some time to compose this page or even just a table of contents that I could fill in?

5. It's a lot of work to create all these manually navigation pages, would @steveparks or @huntons have time to help out with this? We could even create follow up issues to do it per page.

6. Sure, but let's create a new issue to change the design to always be visible and just focus on the IA here.

**Comment by huntons** [comment]
Lewis, as the WunderWay is the new version of the QMS for our ISO certification can you give some consideration to these elements too:

1. Roles and responsibilities - a page describing who's responsible for WW
2. About - a page to describe what the WW is
3. We must have room to write up the scope, the quality policy and quality objectives (I can provide content for this)
4. Continuous improvement and change requests - this fits with the About page (above) to help people understand the purpose of WW and how they can contribute to its improvement

These pages form the basic introduction for the ISO9001 element of WW and will enable me to keep pointing people at the purpose behind the processes that are defined.

**Comment by WunderLemon** [comment]
– Homepage & About
Happy to create a draft of the homepage. I envisaged the external angle being merely along the lines of "How come I can see this?" – a single/two-sentence answer about why we have an open intranet. The homepage shouldn't say much at all, really.

– Visible nav
I've created an issue for this. Sorry I don't quite twig the way about these things sometimes. I'll improve with practice!

– ISO9001 stuffs
It'd be good to get a proper handle on IOS9001 and exactly how it influences WunderWay. I was under the impression it merely influenced content, but now I see it actually influences the reason for its very existence!
Perhaps SteveH and I could have a quick chat through this sometime soon? It's really important for me to understand the situation if I'm to design/create/produce the right kind of content for all purposes, in the right tone of voice for all users.

**Comment by lewisnyman** [comment]
> About - a page to describe what the WW is
@huntons We have this page already on the top level navigation called ["About this site"](http://wunderway.lewisnyman.co.uk/about-this-site/) do you think an improvement would be to all it "About the WunderWay?" I was thinking about first-timers who make not realise what the WunderWay is but we could make it more clear on the home page.

> Roles and responsibilities - a page describing who's responsible for WW
This makes sense as a sub-page of the "about the wunderway" page, care to write it up? @huntons? :)

>  We must have room to write up the scope, the quality policy and quality objectives
I'm unsure where this stuff should sit, at the moment I have it QMS stuff [here](http://wunderway.lewisnyman.co.uk/working-at-wunderkraut/quality-management/) under "Working at Wunderkraut

> Continuous improvement and change requests - this fits with the About page (above) to help people understand the purpose of WW and how they can contribute to its improvement
We have the new [How to edit the Wunderway.](http://wunderway.lewisnyman.co.uk/about-this-site/how-edit-wunderway/)  page—how can we improve it? We can do that in another issue I think.

**Comment by huntons** [comment]
@lewisnyman I'll write up the responsibilities and also include a description about how to request changes to WW

**Pull request merged**
