### PR TITLE
Incorporate the content of Vesa's Security Policy document into WunderWay security section. Fixes wunderkraut/WunderWay#108

### PR DESCRIPTION
**Pull request by joesb**

### CODE REVIEW

**Comment by lewisnyman** [comment]
I merged this locally and it looks good. I think we need @huntons to sign off on this

**Comment by joesb** [comment]
When this is merged, this fixes #108

**Comment by huntons** [comment]
I'm going to create a separate page with the "5 simple steps" else this distracts from official Security Policy

**Comment by joesb** [comment]
If you think that's the right approach, great - I thought this worked well as a more human intro to the security policy than the list that exists on this page, but if that's what you think is the right approach, great.

**Comment by huntons** [comment]
What I don't want to happen is for people to assume that this is all there is to information security. The ISO standard needs a security policy statement from us and to include some parts of the policy here might confuse things a little. The auditors can be a picky bunch

**Comment by joesb** [comment]
Ace, makes perfect sense.

**Pull request closed without merging**
