### PR TITLE
Add Strava club and widgets to WunderFitness page; separate out UK Tour de Wunder

### PR DESCRIPTION
**Pull request by joesb**

### CODE REVIEW

**Comment by lewisnyman** [comment]
Have we replaced MapMyRun with Strava? Do we need to keep the reference to the Wunder Tour? Is there a better way to do this in Strava?

**Comment by joesb** [comment]
Nope, not replaced MapMyRun with Strava necessarily - just that MapMyRun is closed group with only UK members. Strava group is open and has members from all across Wunder
https://www.strava.com/clubs/wunder

**Comment by huntons** [comment]
I'm continuing to use MapMyRun and importing the data into Strava

**Comment by joesb** [comment]
On a personal note, I use an external device on my bike (Garmin Edge 810) and upload to both Strava (I've used Strava for a number of years, before joining Wunder days) and MapMyRun (for UK Tour de Wunder) after a ride.

**Comment by huntons** [comment]
I'm happy to merge this.

**Pull request merged**
