### PR TITLE
Nine Commandments of Design

### PR DESCRIPTION
**Pull request by huntons**
Pushing Matti’s commandments into the “Delivering Projects” section

### CODE REVIEW

**Comment by huntons** [comment]
@lewisnyman  I've created a new section in "Delivering Projects" to house Matti's Commandments of Design

**Comment by lewisnyman** [comment]
@huntons Nice, Can we create a general 'design' section and then put this page within that? I think we are going to add to the design section soon.

**Comment by huntons** [comment]
@lewisnyman there's a "design" heading in the Delivering Projects page. Is that what you meant or did you want another top-level section for design?

**Comment by lewisnyman** [comment]
@huntons There is one now? I don't see it. Having it inside of Delivering Projects makes sense.

**Comment by huntons** [comment]
@lewisnyman it's in this PR and not live yet

**Comment by lewisnyman** [comment]
Doh, I get it now. This content has already been peer reviewed by designers across multiple offices. I'm happy with the IA.

**Pull request merged**
