### PR TITLE
Adds page for best practices in writing developer documentation

### PR DESCRIPTION
**Pull request by joesb**
Fixes wunderkraut/WunderWay#95

### CODE REVIEW

**Comment by joesb** [comment]
@james-nesbitt and @CBones it would be great if you could review this PR

**Comment by CBones** [comment]
For me it looks ok.

**Comment by tharna** [comment]
Is there still something blocking this?
For me this seems like an excelent baseline for now and should be published for further feedback from wider audience.

**Comment by huntons** [comment]
@tharna I don't think there is a blocker other than project work. Perhaps you or @joesb could add this to the Tech Taskforce agenda?

**Comment by joesb** [comment]
@tharna I'm happy for this to be merged, if you're happy with it. Since I created the Pull Request, I'd rather someone else hit the magic green button to merge.

@huntons On the Technology Taskforce involvement, at this stage I think it'd be good to get the content added and then re-iterate for changes as necessary - are you happy with that?

**Comment by huntons** [comment]
@joesb add and re-iterate gets my vote

**Comment by joesb** [comment]
Yay!

**Pull request merged**
